# Ansible
# https://docs.ansible.com/ansible/latest/collections/cisco/aci/aci_bd_module.html#ansible-collections-cisco-aci-aci-bd-module
# APIC
# Tenants > Tenant > Networking > Bridge Domains
- name: Bridge Domains
  ignore_errors: yes
  cisco.aci.aci_bd:
    hostname: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    tenant: "{{ item.Tenant_name }}"
    vrf: "{{ item.VRF_name | default(omit) }}"
    bd: "{{ item.BD_name }}"
    enable_routing: "{% if item.bd_type is defined and item.bd_type == 'fc' %}no{% else %}{{ item.enable_routing | default('no') }}{% endif %}"
    mac_address: "{{ Gateway_MAC_address | default(omit) }}"
    arp_flooding: "{{ item.arp_flooding | default('yes') }}"
    l2_unknown_unicast: "{{ item.l2_unknown_unicast | default('proxy') }}"
    l3_unknown_multicast: "{{ item.l3_unknown_multicast | default(omit) }}"
    bd_type: "{{ item.bd_type | default(omit) }}"
    state: "{% if item.bd_state is defined and item.bd_state == 'absent' %}absent{% else %}present{% endif %}"
  with_items: "{{ BridgeDomains_Subnets }}"
  loop_control:
    pause: "{{ loop_control_pause | default(0) }}"

# Ansible
# https://docs.ansible.com/ansible/latest/collections/cisco/aci/aci_bd_subnet_module.html#ansible-collections-cisco-aci-aci-bd-subnet-module
# APIC
# Tenants > Tenant > Networking > Bridge Domains > Subnets
- name: Bridge Domain Subnets
  ignore_errors: yes
  cisco.aci.aci_bd_subnet:
    hostname: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    tenant: "{{ item.Tenant_name }}"
    bd: "{{ item.BD_name }}"
    gateway: "{{ item.bd_subnet }}"
    mask: "{{ item.bd_subnet_mask }}"
    scope: "{{ item.scope | default(omit) }}"
    state: "{% if item.bd_state is defined and item.bd_state == 'absent' %}query{% else %}present{% endif %}"
  with_items: "{{ BridgeDomains_Subnets }}"
  when: item.bd_subnet is defined and item.bd_subnet_mask is defined
  loop_control:
    pause: "{{ loop_control_pause | default(0) }}"

# Ansible
# https://docs.ansible.com/ansible/latest/collections/cisco/aci/aci_bd_to_l3out_module.html#ansible-collections-cisco-aci-aci-bd-to-l3out-module
# APIC
# Tenants > Tenant > Networking > Bridge Domains > Policy > L3 Configurations
- name: Associate L3Out to Bridge Domain
  ignore_errors: yes
  cisco.aci.aci_bd_to_l3out:
    hostname: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    tenant: "{{ item.Tenant_name }}"
    bd: "{{ item.BD_name }}"
    l3out: "{{ item.advertise_via_l3out }}"
    state: "{% if item.bd_state is defined and item.bd_state == 'absent' %}query{% else %}present{% endif %}"
  with_items: "{{ BridgeDomains_Subnets }}"
  when: item.advertise_via_l3out is defined
  loop_control:
    pause: "{{ loop_control_pause | default(0) }}"