# Ansible
# https://docs.ansible.com/ansible/latest/collections/cisco/mso/mso_schema_template_anp_epg_module.html#ansible-collections-cisco-mso-mso-schema-template-anp-epg-module
# MSO
# Application Management > Schemas > Templates > SITE > AP > EPG > Domains

- name: MSO Domain in EPG - Site level
  ignore_errors: yes
  cisco.mso.mso_schema_site_anp_epg_domain:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    login_domain: "{{ login_domain | default(omit) }}"
    validate_certs: no
    schema: "{{ item.Schema_name }}"
    template: "{{ item.Template_name }}"
    site: "{{ item.Site }}"
    anp: "{{ item.AppProfile_name }}"
    epg: "{{ item.EPG_name }}"
    domain_association_type:  "{{ item.domain_type }}"
    domain_profile: "{{ item.domain_name }}"
    deployment_immediacy: lazy
    resolution_immediacy: lazy
    state: present
  with_items: "{{ EPGs_Domains_Static_Bindings_Site_level }}"
  when: (item.domain_name is defined) and (item.domain_type is defined)
  loop_control:
    pause: "{{ loop_control_pause | default(0) }}"

# Ansible
# https://docs.ansible.com/ansible/latest/collections/cisco/mso/mso_schema_template_anp_epg_module.html#ansible-collections-cisco-mso-mso-schema-template-anp-epg-module
# MSO
# Application Management > Schemas > Templates > SITE > AP > EPG > Static ports

- name: MSO Static Ports in EPG - Site level
  ignore_errors: yes
  cisco.mso.mso_schema_site_anp_epg_staticport:
    host: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    login_domain: "{{ login_domain | default(omit) }}"
    validate_certs: no
    schema: "{{ item.0.Schema_name }}"
    template: "{{ item.0.Template_name }}"
    site: "{{ item.0.Site }}"
    anp: "{{ item.0.AppProfile_name }}"
    epg: "{{ item.0.EPG_name }}"
    pod: "{{ item.1.Pod }}"
    leaf: "{{ item.1.Leaf }}"
    type: "{{ item.1.type }}"
    path: "{{ item.1.port }}"
    vlan: "{{ item.0.Encap_VLAN }}"
    mode: "{% if item.1.native_vlan is defined and item.1.native_vlan == item.0.Encap_VLAN %}native{% else %}regular{% endif %}"
    state: "{{ item.1.state | default('present', true) }}"
  with_subelements: 
  - "{{ EPGs_Domains_Static_Bindings_Site_level }}"
  - Static_Binding
  - flags:
    skip_missing: True
  loop_control:
    pause: "{{ loop_control_pause | default(0) }}"