################################################################################
# v0.14 2021-May-27                                                            #
# This Ansible playbook comes with no guarantees                               #
# The use of this Ansible playbook is responsibility solely of who executes it #
# No liabilities shall be deemed to the creator of this Ansible playbook       #
#                                                                              #
################################################################################

- name: ACI playbook
  hosts: apicsim_sandbox_example
  connection: local
  gather_facts: no

  vars:
    loop_control_pause: 0           # Adds a delay between loop iterations. Required when the APIC cannot handle the rate of all the connections

  roles:
  ###############################
  #                             #
  #       Access Policies       #
  #                             #
  ###############################

  - Interface_Policies              # CDP, LLDP, Fibre Channel, MCP, Link Level, Port Channel, Spanning Tree Interface policies
  - Switch_and_Interface_Profiles   # Add Switches Profiles and Interface Profiles (needed when adding new switches to ACI)

  - Interface_Selectors             # Assigns the previous items to specific ports on the Switches
  - Interface_Policy_Groups         # Creates Interface Access Port, Port-Channels and vPCs
  - enable_or_disable_ports         # Interfaces (regular operation)

  - AAEPs                           # AAEPs, Domains and VLAN Pools
  - Domains
  - VLAN_Pools

  ###############################
  #                             #
  #           Tenants           #
  #                             #
  ###############################

  - Tenants_and_VRFs
  - BridgeDomains_and_Subnets
  - AppProfiles_and_EPGs
  - Domains_and_EPG_Static_Bindings
  - Associate_L3Out_in_BridgeDomain

  ############ L3Outs ############

  - L3Out_vPC_SVI
  - L3Out_PortChannel_SubIntf_OSPF
  - L3Out_Port_SVI_BGP

  ########### Contracts ###########

  - vzAny                           # 'permit any' for all the EPGs in the VRF
  - EPG_to_EPG_Contracts