################################################################################
# v0.36 2021-June-18                                                           #
# This Ansible playbook comes with no guarantees                               #
# The use of this Ansible playbook is responsibility solely of who executes it #
# No liabilities shall be deemed to the creator of this Ansible playbook       #
#                                                                              #
# Ansible playbook hosted in                                                   #
# https://github.com/gustavos86/OperatingCiscoACIwithAnsible                   #
################################################################################

- name: MSO playbook
  hosts: mso_sandbox_example
  connection: local
  gather_facts: no

  vars:
    loop_control_pause: 0          # adds a delay between loop iterations. Required if the MSO cannot handle the rate of all the connections

  roles:
  ###############################
  #                             #
  #   Multi-Site Orchestrator   #
  #                             #
  ###############################

  - { role: MSO_Tenants_Sites,                   tags: tenants         }
  - { role: MSO_Schemas_Templates,               tags: schemas         }
  - { role: MSO_VRFs,                            tags: vrfs            }
  - { role: MSO_BridgeDomains_and_Subnets,       tags: bds             }
  - { role: MSO_AppProfiles,                     tags: aps             }
  - { role: MSO_EPGs,                            tags: epgs            }
  - { role: MSO_Domains_and_EPG_Static_Bindings, tags: staticbindings  }
  - { role: MSO_L3Outs,                          tags: l3outs          }
  - { role: MSO_Deploy_action,                   tags: [deploy, never] }