# Ansible
# https://docs.ansible.com/ansible/latest/collections/cisco/aci/aci_interface_policy_leaf_policy_group_module.html#ansible-collections-cisco-aci-aci-interface-policy-leaf-policy-group-module
# APIC
# Fabric > Access Policies > Interfaces > Leaf Interfaces > Policy Groups > Leaf Access Port
# Fabric > Access Policies > Interfaces > Leaf Interfaces > Policy Groups > PC Interface
# Fabric > Access Policies > Interfaces > Leaf Interfaces > Policy Groups > VPC Interface
- name: Access Ports, Port-Channels & vPCs
  ignore_errors: yes
  cisco.aci.aci_interface_policy_leaf_policy_group:
    hostname: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    validate_certs: no
    policy_group: "{{ item.interface_policy_group }}"
    lag_type: "{{ item.lag_type }}"
    # port_channel_policy must be ommited when lag_type: leaf
    port_channel_policy: "{% if item.lag_type != 'leaf' %}{{ item.port_channel_policy }}{% else %}{{ item.DummyItem | default(omit) }}{% endif %}"
    aep: "{{ item.AAEP | default(omit) }}"
    link_level_policy: "{{ item.link_level_policy | default(omit) }}"
    cdp_policy: "{{ item.cdp_policy | default(omit) }}"
    lldp_policy: "{{ item.lldp_policy | default(omit) }}"
    mcp_policy: "{{ item.mcp_policy | default(omit) }}"
    stp_interface_policy: "{{ item.stp_interface_policy | default(omit) }}"
    l2_interface_policy: "{{ item.l2_interface_policy | default(omit) }}"
    fibre_channel_interface_policy: "{{ item.fibre_channel_interface_policy | default(omit) }}"
    priority_flow_control_policy: "{{ item.priority_flow_control_policy | default(omit) }}"
    monitoring_policy: "{{ item.monitoring_policy | default(omit) }}"
    state: "{{ whattodo | default('present', true) }}"      
  with_items: "{{ Interface_Policy_Group_task_config }}"
  loop_control:
    pause: "{{ loop_control_pause | default(0) }}"