# Ansible
# https://docs.ansible.com/ansible/latest/collections/cisco/aci/aci_aep_module.html#ansible-collections-cisco-aci-aci-aep-module
# APIC
# Fabric > Access Policies > Policies > Global > Attachable Access Entity Profile
- name: Attachable Access Entity Profiles (AAEP)
  cisco.aci.aci_aep:
    hostname: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    aep: "{{ item.name }}"
    infra_vlan: no
    state: "{{ whattodo | default('present', true) }}"
  with_items: 
    - "{{ AAEP_task_config }}"

# Ansible
# https://docs.ansible.com/ansible/latest/collections/cisco/aci/aci_aep_to_domain_module.html#ansible-collections-cisco-aci-aci-aep-to-domain-module
# APIC
# Fabric > Access Policies > Policies > Global > Attachable Access Entity Profile
- name: Attach Domains to AAEPs
  cisco.aci.aci_aep_to_domain:
    hostname: "{{ ansible_host }}"
    username: "{{ username }}"
    password: "{{ password }}"
    aep: "{{ item.0.name }}"
    domain_type: "{{ item.1.domain_type }}"
    domain: "{{ item.1.domain_name }}"
    state: "{{ whattodo | default('present', true) }}"
  with_subelements: 
    - "{{ AAEP_task_config }}"
    - domains
